name: CI and Deploy

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm run install

      - name: Start server and client
        run: npm run develop &
        env:
          NODE_ENV: development
      
      - name: Check server logs
        run: sleep 5 && curl http://localhost:3001 || echo "Server not responding after 5 seconds."  

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3001

      - name: Run Cypress tests
        run: npm run test

      - name: Deploy
        if: github.ref == 'refs/heads/main' && success()
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"